[Projects]
; Format: project name = path/to/project
; Project names and paths are case sensitive
; Paths must either be absolute, or relative to the Grapple executable
; Paths can optionally use quotes, and use single or double slashes (forward or backward)
projectA=relative/path/to/project
projectB = "C:\\absolute//path/to/project"
