[Projects]
; Format: project name = path/to/project
; Project names and paths are case sensitive
; Paths must either be absolute, or relative to the Grapple executable
; Quotation marks are not currently supported.
projectA=relative/path/to/project
projectB = C:\\absolute//path/to/project
